# Generated by Django 5.2.3 on 2025-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
