# Generated by Django 5.2.3 on 2025-08-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chair',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chair',
            name='x_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chair',
            name='y_position',
            field=models.FloatField(default=0.0),
        ),
    ]
