# Generated by Django 5.2.3 on 2025-08-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
        ('owner', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keyword', to='tag.tag'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
        migrations.CreateModel(
            name='CafeTagRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
            options={
                'unique_together': {('cafe', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cafes', through='cafe.CafeTagRating', to='tag.tag'),
        ),
    ]
